name: Add resource
description: Request adding a paper/code/tutorial
labels: [addition]
body:
  - type: markdown
    attributes:
      value: |
        Please follow the README entry format:
        `- Title (Venue Year) [paper](https://doi.org/... or journal) [code](https://github.com/...) [project](https://...)`
        For arXiv, use `[arxiv](https://arxiv.org/abs/...)` instead of `[paper](...)`.
  - type: input
    id: title
    attributes: { label: Title, placeholder: Paper or resource title }
    validations: { required: true }
  - type: input
    id: venue
    attributes: { label: Venue/Year, placeholder: e.g., CVPR 2024 }
  - type: input
    id: paper
    attributes: { label: Paper link (DOI/journal or arXiv), placeholder: https:// }
  - type: input
    id: arxiv
    attributes: { label: arXiv link (if applicable), placeholder: https://arxiv.org/abs/... }
  - type: input
    id: code
    attributes: { label: Code link (optional), placeholder: https://github.com/... }
  - type: input
    id: project
    attributes: { label: Project page (optional), placeholder: https:// }
  - type: textarea
    id: summary
    attributes: { label: One‑sentence summary (optional) }
  - type: dropdown
    id: section
    attributes:
      label: Section
      options: [Papers, Datasets & Benchmarks, Libraries & Tooling, Tutorials & Talks]
    validations: { required: true }
