name: Broken link
description: Report a dead or redirected link
labels: [broken-link]
body:
  - type: input
    id: url
    attributes: { label: URL, placeholder: https:// }
    validations: { required: true }
  - type: textarea
    id: context
    attributes: { label: Where it appears (section/line) }

