name: link-check
on:
  pull_request:
  schedule:
    - cron: '0 6 * * 1'
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --timeout 20s README.md CONTRIBUTING.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
